import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {useState} from 'react'; 



export default function Home() {

const [area, setArea] = useState('')

const display = (e) => {
  setArea(area + e.target.value);
}

const clear = () => {
  setArea('');
}





  return (
    <>
      <Head>
        <title>Creations by Nick Hurd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

<div className={styles.area}> {area} </div>


       <div className={styles.calculatorBase}>


<button className={styles.calcButton} onClick={display} value= '0' > 0 </button>
<button className={styles.calcButton} onClick={display} value= '1' > 1 </button>
<button className={styles.calcButton} onClick={display} value= '2' > 2 </button>
<button className={styles.calcButton} onClick={display} value= '3' > 3 </button>
<button className={styles.calcButton} onClick={display} value= '4' > 4 </button>
<button className={styles.calcButton} onClick={display} value= '5' > 5 </button>
<button className={styles.calcButton} onClick={display} value= '6' > 6 </button>
<button className={styles.calcButton} onClick={display} value= '7' > 7 </button>
<button className={styles.calcButton} onClick={display} value= '8' > 8 </button>
<button className={styles.calcButton} onClick={display} value= '9' > 9 </button>
<button className={styles.calcButton} onClick={display} value= '.' > . </button>
<button className={styles.calcButton} onClick={display} value= {'+'} > + </button>
<button className={styles.calcButton} onClick={display} value= '-' > - </button>
<button className={styles.calcButton} onClick={display} value= '%' > % </button>
<button className={styles.calcButton} onClick={display} value= '*' > * </button>
<button className={styles.calcButton} onClick={display} value= '=' > = </button>
<button className={styles.calcButton} onClick={clear} > Clear </button>



       </div>
       
       <div className="footer">
<footer>
  <p> Created by: <em>Nicholas Hurd</em></p>
</footer>
</div>
        </main>
    </>
  )
}
